import { readFileSync, readdirSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * Every PostgREST embed must name a relationship the schema actually has, and
 * name it unambiguously.
 *
 * Two production outages hide in this one gap, and neither the build nor the
 * type checker could see either, because a `.select()` is a string:
 *
 *   PGRST200 -- `listRecipes` asked for `field_evidence_count:field_evidence
 *   (count)`, embedding `field_evidence` from `recipes`. PostgREST resolves an
 *   embed by walking a foreign key, and `field_evidence` is polymorphic: it
 *   points at a recipe, a recipe item or a recipe step through `entity_type` +
 *   `entity_id`, with no foreign key to any of them. The relationship asked
 *   for does not exist and cannot be made to exist.
 *
 *   PGRST201 -- three queries embedded `recipe_items` from `recipes`, which has
 *   *two* foreign keys back to it: `recipe_id` for a recipe's own lines and
 *   `component_recipe_id` for the recipes that use it as a component. Two
 *   candidates is as unusable as none, and PostgREST refuses until one is
 *   named with `!constraint`.
 *
 * This reads the foreign keys out of the migrations and the embeds out of the
 * repository and insists the two agree. It is the check that was missing.
 */

const ROOT = process.cwd()
const MIGRATIONS = path.join(ROOT, 'supabase', 'migrations')
const REPOSITORY = path.join(ROOT, 'src', 'lib', 'data', 'supabase', 'repository.ts')

interface ForeignKey {
  table: string
  references: string
  column: string
}

/**
 * Splits a `create table` body into its top-level definitions.
 *
 * On commas at paren depth zero, so `numeric(10, 2)` stays one definition and a
 * column whose `references` clause sits on the next line stays attached to the
 * column it belongs to.
 */
function definitions(body: string): string[] {
  const parts: string[] = []
  let depth = 0
  let current = ''

  for (const char of body) {
    if (char === '(') depth += 1
    if (char === ')') depth -= 1
    if (char === ',' && depth === 0) {
      parts.push(current)
      current = ''
      continue
    }
    current += char
  }
  parts.push(current)

  // Comments carry the word "references" in prose often enough to matter.
  return parts.map((part) => part.replace(/--[^\n]*/g, '').trim()).filter(Boolean)
}

/**
 * The foreign keys, read from the migrations.
 *
 * Deliberately parsed from the SQL rather than from a generated types file:
 * the types are regenerated by hand and can lag, while the migrations are what
 * the database was built from.
 */
function foreignKeys(): ForeignKey[] {
  const keys: ForeignKey[] = []

  for (const file of readdirSync(MIGRATIONS).sort()) {
    if (!file.endsWith('.sql')) continue
    const sql = readFileSync(path.join(MIGRATIONS, file), 'utf8')

    for (const table of sql.matchAll(
      /create table (?:if not exists\s+)?(\w+)\s*\(([\s\S]*?)\n\);/g,
    )) {
      const [, name, body] = table

      for (const definition of definitions(body!)) {
        const target = /\breferences\s+(?:\w+\.)?(\w+)\s*\(/.exec(definition)
        if (!target) continue

        // Table-level `foreign key (col) references Y (...)`, or the ordinary
        // column-level form where the definition opens with the column name.
        const tableLevel = /^foreign key\s*\((\w+)\)/i.exec(definition)
        const column = tableLevel ? tableLevel[1]! : (/^(\w+)/.exec(definition)?.[1] ?? '')
        if (!column || /^(constraint|unique|primary|check)$/i.test(column)) continue

        keys.push({ table: name!, references: target[1]!, column })
      }
    }

    // Keys added to a table that already exists.
    for (const altered of sql.matchAll(
      /alter table (?:only\s+)?(\w+)[\s\S]{0,200}?foreign key\s*\((\w+)\)\s*references\s+(?:\w+\.)?(\w+)\s*\(/g,
    )) {
      keys.push({ table: altered[1]!, references: altered[3]!, column: altered[2]! })
    }
  }

  return keys
}

/** Foreign keys joining two tables, in either direction: PostgREST walks both. */
function between(keys: ForeignKey[], a: string, b: string): ForeignKey[] {
  return keys.filter(
    (key) => (key.table === a && key.references === b) || (key.table === b && key.references === a),
  )
}

interface Embed {
  parent: string
  table: string
  /** True when the select names a constraint with `!`, resolving ambiguity. */
  disambiguated: boolean
  from: string
}

/**
 * Every table embedded in a `.select(...)`, with the table it hangs off.
 *
 * PostgREST select syntax nests: `a (b (c))` embeds `b` in `a` and `c` in `b`.
 * The parser tracks that nesting, strips the `alias:` prefix, records whether a
 * `!constraint` hint was given, and ignores `count`, which is an aggregate
 * rather than a table.
 */
function embeds(): Embed[] {
  const source = readFileSync(REPOSITORY, 'utf8')
  const found: Embed[] = []

  for (const call of source.matchAll(
    /\.from\('(\w+)'\)[\s\S]{0,80}?\.select\(\s*(`[\s\S]*?`|'[^']*')/g,
  )) {
    const from = call[1]!
    const body = call[2]!.slice(1, -1)
    const stack: string[] = [from]

    // Walked with a cursor so nesting depth stays in step with the table each
    // embed belongs to.
    const token = /([A-Za-z_]\w*)\s*(!\w+)?\s*\(|\)/g
    let match: RegExpExecArray | null
    while ((match = token.exec(body))) {
      if (match[0] === ')') {
        if (stack.length > 1) stack.pop()
        continue
      }
      const name = match[1]!
      const parent = stack[stack.length - 1]!
      if (name === 'count') {
        stack.push(parent)
        continue
      }
      found.push({ parent, table: name, disambiguated: Boolean(match[2]), from })
      stack.push(name)
    }
  }

  return found
}

describe('the foreign keys the migrations declare', () => {
  const keys = foreignKeys()

  it('are parsed out of the migrations at all', () => {
    expect(keys.length).toBeGreaterThan(30)
    expect(between(keys, 'recipe_items', 'recipes').length).toBeGreaterThan(0)
    expect(between(keys, 'recipe_translations', 'recipes')).toHaveLength(1)
  })

  it('join recipe_items to recipes twice, which is why the embed needs naming', () => {
    const both = between(keys, 'recipe_items', 'recipes')
      .map((key) => key.column)
      .sort()
    expect(both).toEqual(['component_recipe_id', 'recipe_id'])
  })

  it('do not connect recipes to field_evidence, because it is polymorphic', () => {
    expect(between(keys, 'recipes', 'field_evidence')).toEqual([])

    const init = readFileSync(path.join(MIGRATIONS, '20260817000100_init.sql'), 'utf8')
    const table = /create table field_evidence\s*\(([\s\S]*?)\n\);/.exec(init)?.[1] ?? ''
    expect(table).toMatch(/entity_type text not null check/)
    expect(table).toMatch(/entity_id uuid not null/)
    // Whatever else changes, `entity_id` must not gain a foreign key: it holds
    // ids from three tables, and a key to any one of them would reject every
    // row belonging to the other two.
    expect(table).not.toMatch(/entity_id[^,\n]*references/)
  })
})

describe('every embed the repository asks PostgREST for', () => {
  const keys = foreignKeys()
  const all = embeds()

  it('finds the embeds to check', () => {
    expect(all.length).toBeGreaterThan(20)
    expect(all.some((embed) => embed.table === 'recipe_translations')).toBe(true)
    // The exact query that took production down, now shaped correctly.
    expect(
      all.some(
        (embed) =>
          embed.from === 'recipes' && embed.table === 'recipe_items' && embed.disambiguated,
      ),
    ).toBe(true)
  })

  it('walks a foreign key that actually exists', () => {
    const unresolvable = all
      .filter((embed) => between(keys, embed.parent, embed.table).length === 0)
      .map((embed) => `${embed.from}: ${embed.parent} -> ${embed.table}`)

    // Each entry here is a PGRST200 waiting for the page that runs it.
    expect([...new Set(unresolvable)]).toEqual([])
  })

  it('names the constraint wherever two tables are joined more than once', () => {
    const ambiguous = all
      .filter(
        (embed) => !embed.disambiguated && between(keys, embed.parent, embed.table).length > 1,
      )
      .map((embed) => `${embed.from}: ${embed.parent} -> ${embed.table}`)

    // Each entry here is a PGRST201 waiting for the page that runs it.
    expect([...new Set(ambiguous)]).toEqual([])
  })

  it('never embeds field_evidence, whatever the parent', () => {
    // The specific mistake, named, so re-introducing it fails here rather than
    // only when someone opens the library in production.
    expect(all.filter((embed) => embed.table === 'field_evidence')).toEqual([])
  })
})
